### ISSUE TITLE
[Todo] project structure

### ISSUE THREAD

**Issue by changchaishi** [NCKU-CCS/fake-info-backend#1]
目前 develop 與 news branch 是一致的，但對於目前 backend 的部分還有些許需要改進的地方

- [x] Pipfile: Pipfile 內部的套件版本需要寫死。例如將 `fastapi = "*"`  -> `fastapi = "==x.x.x", 需要這樣做是因為，我們在創建 project時（尤其是公開性的 project）我們希望我們的 project 是保持一致性的，所以 pipenv 搭配指定性的套件能幫我們辦到這點。如果有興趣可以查看 `什麼是 deterministc program`。
- [x] (`docker-compose.yml`) Database 的 user password 應該寫在  `.env` 或者環境變數 ，或者 user name 取一個適合大家所使用的的 user 例如 netdb, netdb2602。
- [x] 將不需要的套件從 pipfile 移除如 flask
- [x] 修正 typo 與 trailing spaces
- [x] 新增 gitignore (將 `__pycache__` 等等不必要的資料加入）
- [x] 新增 readme
- [x] 分開 `main.py` 檔案, 避免所有邏輯寫在一個檔案
---
phase 2
- [ ]  導入 pylint
- [x] dockerize fastapi, 新增 dockerfile, 加入 api 至 docker-compose

**Comment by changchaishi** [comment]
done by . #4
